### ISSUE TITLE
Add support to deploy from a branch within the selected repo

### ISSUE THREAD

**Issue by sswigercs** [afawcett/githubsfdeploy#14]
Could you add support to pull the branches for the selected repo and display in a combobox (defaulted to master) on the githubdeploy.jsp, then utilize the selected branch for the deploy? 
As a side note, this could be dependent on #1 because the branches could have a dot (.) in them.
Thanks!

**Comment by afawcett** [comment]
Yep, added to the list! Thanks for the suggestion. :+1:

**Comment by dshahin** [comment]
:+1:

**Comment by dshahin** [comment]
Great idea!  The ability to deploy branches would be a huge feature.

**Comment by ImJohnMDaniel** [comment]
Hey @afawcett.  Any movement on this enhancement, by chance?  Any thoughts about how to implement?  I ask because I have a similar requirement and this feature might just do the trick. Please let me know when you can.  Cheers!

**Comment by afawcett** [comment]
Yep i'll get on this soon!

**Comment by afawcett** [comment]
Done! 👍 Blog on its way.
