### ISSUE TITLE
Error in GitHub Deploy Tool : Sandbox Support

### ISSUE THREAD

**Issue by harmoney-vikramk** [afawcett/githubsfdeploy#15]
I tried to use the link given to use Deploy to sandbox. It throws the below error message. Screenshot below.

classes/SObjectDataLoaderTest.cls(521,87):Method does not exist or incorrect signature: [SObjectDataLoader.SerializeConfig].addToUserFieldBlackList(Map>)

![image](https://cloud.githubusercontent.com/assets/12439465/13449387/c8687ae8-e08f-11e5-84c5-6f3bb5eff536.png)

**Comment by afawcett** [comment]
This issues belongs in another repo https://github.com/afawcett/apex-sobjectdataloader/issues/19, please track it over there.
