### ISSUE TITLE
Github API responds with 404 for user owned fork of an Organisation's private repository

### ISSUE THREAD

**Issue by nathanKramer** [afawcett/githubsfdeploy#16]
@afawcett re our twitter conversation
I hit an issue with the tool that took me a while to figure out at first.

I tried to deploy a fork of a private repository which was owned by an Organisation I have access to.
`Unhandled Exception : org.eclipse.egit.github.core.client.RequestException: Not Found (404)`

Since it was _my fork_ that was I attempting to deploy, I assumed that it would be treated as a regular private repository, and therefore the OAuth permissions that the tool requests should be sufficient, but it seems that since it is a fork of a repository I do not own, the parent Organisation has control over whether or not the client application can see the repository.

This can probably be put on the user to resolve by requesting access from an Organisation administrator.
I have a branch with some basic user feedback which I have just tested, so I can open a PR for you to take a look at.

**Comment by nathanKramer** [comment]
In short, I didn't know about how [Third Party Restrictions](https://help.github.com/articles/about-third-party-application-restrictions/) work on Github

**Comment by afawcett** [comment]
Thanks, great insight! :+1:

**Comment by afawcett** [comment]
Looks like i need to upgrade my Cedar platform on Heroku, i'll push this update in the next few days and close out this issue. Thanks again!

**Comment by afawcett** [comment]
I've got this upgraded locally, going to make some enhancements, then i'll push your changes here as well.

**Comment by afawcett** [comment]
I have now deployed this change. Thanks! :+1:
