### ISSUE TITLE
Badge style deploy icon + markdown

### ISSUE THREAD

**Issue by jdcrensh** [afawcett/githubsfdeploy#18]
It's become fairly common to see badges (eg: [shields.io](http://shields.io/)) in project READMEs being used for various purposes (build status, coverage, etc). Perhaps this project could switch to providing a deploy icon styled in a similar way, and provided as markdown.

[![deploy to salesforce](https://img.shields.io/badge/salesforce-deploy-blue.svg)](https://githubsfdeploy.herokuapp.com)

``` markdown
[![deploy to salesforce](https://img.shields.io/badge/salesforce-deploy-blue.svg)](https://githubsfdeploy.herokuapp.com)
```

**Comment by afawcett** [comment]
This is brilliant, how did you create it?

**Comment by jdcrensh** [comment]
I can't take much credit for that. I used "Your Badge" generator near the bottom of [shields.io](shields.io) to build the URL. :wine_glass:
