### ISSUE TITLE
Duplicate Username Error

### ISSUE THREAD

**Issue by rashminirmal** [afawcett/githubsfdeploy#20]
ChatterOrgChartControllerTest class 	test_get_users method returned this error : System.DmlException: Insert failed. First exception on row 0; first error: DUPLICATE_USERNAME, Duplicate Username.<br>The username already exists in this or another Salesforce organization. Usernames must be unique across all Salesforce organizations. To resolve, use a different username (it doesn't need to match the user's email address). : [Username] 
Stack Trace: Class.ChatterOrgChartControllerTest.test_get_users: line 40, column 1

**Comment by DouglasCAyers** [comment]
Thanks @rashminirmal. This is being handled at https://github.com/DouglasCAyers/sfdc-chatter-org-chart/pull/4

**Comment by afawcett** [comment]
Thanks @DouglasCAyers, i'll close this issue out then, thanks for the update!
