### ISSUE TITLE
OAuth error when deploying package

### ISSUE THREAD

**Issue by renatoliveira** [afawcett/githubsfdeploy#21]
Trying to deploy the following package:

https://githubsfdeploy.herokuapp.com/?owner=SalesforceFoundation&repo=visualforce-typeahead

gives me the following error:

> Oops, something went wrong...
> Authentication Failed: OAuth login invalid or expired access token
> Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

When I clicked the link, Production / Develoepr was the option, and I didn't change the names of the owner or repository. The organization is a Developer Edition, do I need to change some configuration on the org to allow the tool to do its job?

If not, then might this be related to Salesforce dropping support for TLS 1.0?

**Comment by jdrishe** [comment]
Hello Andy,
As we spoke about on your personal website, also having some trouble with the deploy button to push apex wrapper code to my dev org. Looks like it's the same issue as above.

Steps to reproduce:
I do get the prompt to select production - developer / sandbox as well as the Owner and Repository upon pressing the deploy button.
I leave it as Production - Developer and keep the Owner at financialforcedev and Repo at apex-mdapi.
I then login to my org, it processes, and then gives Oath error.

I do have mydomain turned on, if that matters.

Thanks!
-Joseph

**Comment by afawcett** [comment]
Ok thanks, i'll have a look at this, my domain might be it, does it work in a fresh DE org setup from developer.salesforce.com?

**Comment by renatoliveira** [comment]
Andrew, I don't know if my DE org counts exactly as fresh, but I can tell you that it was created on 15 Mar. It is pretty new, and I only made some minor development (objects and pages). Nothing major that would affect deployments, in my opinion. Almost fresh, I'd say.

**Comment by afawcett** [comment]
Yep looks like a TLS 1.0 issue, standby...

**Comment by afawcett** [comment]
This should be sorted now, can you retry? (close and restart your browser).

**Comment by renatoliveira** [comment]
Yes, it worked now flawlessly! Thank you. Great tool, man!

**Comment by jdrishe** [comment]
worked for me as well, thanks Andy!
