### ISSUE TITLE
Getting an "Application Error" when attempting to deploy fflib-apex-mocks to a Sandbox

### ISSUE THREAD

**Issue by cipherstream** [afawcett/githubsfdeploy#22]
Greetings!  

Thanks so much for providing the GitHub deployment tool.  I've used it successfully to deploy both the fflib-apex-mocks and the apex commons libraries into a couple of different sandboxes.  However, this time, when I'm attempting to deploy the apex mocks library into a "QA" sandbox; I get the following error:

> **Application Error**
> *An error occurred in the application and your page could not be served. Please try again in a few moments.*
> 
> *If you are the application owner, check your logs for details.*

This occurs when I select "sandbox" and have *Owner:* set as *financialforcedev* and *Repository:* set as *fflib-apex-mocks*.

What do you suppose could be my issue?

**Comment by cipherstream** [comment]
Reading the comments in the blog page for this tool, I note that someone else had the same problem back in March.  It appears that you repaired the situation by restarting the Heroku container for that tool.  Do you think the same issue could be causing my error as well?

**Comment by afawcett** [comment]
Try again now, should be fixed.

**Comment by cipherstream** [comment]
Sweet. Problem is solved.  Was the issue with the Heroku instance?

**Comment by afawcett** [comment]
Miss configuration by an admin in a rush! ;-)
