### ISSUE TITLE
Sandbox Deploy doesn't support TLS 1.1+

### ISSUE THREAD

**Issue by scottpelak** [afawcett/githubsfdeploy#23]
First, thanks for the awesome tool.

Today, Monday 2016-06-13, I tried deploying a GitHub project to a Sandbox via [https://githubsfdeploy-sandbox.herokuapp.com/app/githubdeploy/flexchecks/flexchecks](https://githubsfdeploy-sandbox.herokuapp.com/app/githubdeploy/flexchecks/flexchecks).  (_Note:  It's a private repo_)  It asked me to log in to my Sandbox User, but the authentication failed:

> Oops, something went wrong...
> Authentication Failed: OAuth login invalid or expired access token
> Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

II deactivated the "Require TLS 1.1 or higher for HTTPS connections" Salesforce Critical Update, tried the URL again, and I was able to log in and deploy the Github Repo to my Sandbox.

**Comment by afawcett** [comment]
Sorry about that, can you try again please?

**Comment by scottpelak** [comment]
I activated the "Require TLS 1.1 or higher for HTTPS connections" Salesforce Critical Update in my Sandbox, and I'm able to log in successfully.

Thanks!

**Comment by afawcett** [comment]
Excellent!
