### ISSUE TITLE
Failure to deploy due to error parsing content in Readme.md file

### ISSUE THREAD

**Issue by wnourse** [afawcett/githubsfdeploy#24]
Hi Andy, I'm running into the same issue that Kevin Fielding posted to the blog.  I've got a repo (https://github.com/wnourse/apex-guidestar) that won't deploy, throwing the following error:

Deployment Complete
Failures:
customMetadata/README.md(1,1):Error parsing file: Content is not allowed in prolog.

Any idea?

**Comment by afawcett** [comment]
Hmmmm nothing at present, i'll take a look though.

**Comment by ankushsomani09** [comment]
I saw the issued Repo. It doesn't has package.xml file. 
When ever this error appear `Error parsing file: Content is not allowed in prolog.` . It comes due to repo don't have package.xml file in src folder.

**Comment by afawcett** [comment]
@ankushsomani09 great connection, thanks!

**Comment by ankushsomani09** [comment]
@wnourse : It still not solved. I tried renaming file README.Md to README. Then it worked. 
Actually If we keep it readme.md, then while deploying it take this file also in deployment consideration. 

There might be different solution to this, but temporary one is to rename this file.
cc: @afawcett

**Comment by afawcett** [comment]
Thanks for sharing @ankushsomani09

**Comment by jschneider-nexgen** [comment]
FYI.  Renamed file to README.markdown and it ignored the readme during deployment

**Comment by afawcett** [comment]
This has name been fixed.
