### ISSUE TITLE
OAuth Error after access granted

### ISSUE THREAD

**Issue by ghost** [afawcett/githubsfdeploy#25]
- New Developer Edition organization, no IP restrictions
- "Grant access" dialog appears after clicking on the "Login to Salesforce" button
- OAuth Error message after access granted:
  > Oops, something went wrong...
  > Authentication Failed: OAuth login invalid or expired access token
  > Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

URL looks correctly:
https://githubsfdeploy.herokuapp.com/_auth?code=aPrxSV6UAcNrPEkEccurRd63fzSaoVf49aHsFeMABXkEjhzzsxq0wn8MJxoNdc5pfT_SE0GZEw%3D%3D&state=https%3A%2F%2Fgithubsfdeploy.herokuapp.com%2Fapp%2Fgithubdeploy%2FTestOwner%2FTestRepo

It works in my old DE, but it doesn't in the newly created one.
I logged out, switched the user and revoked OAuth connected app with no result.

**Comment by LarryKlugerDS** [comment]
Thank you for the software! Unfortunately I'm having the same issue as @skoritsbl . Everything was working fine, but now I receive the oauth failure with a fresh DE after approving OAuth access to the button:

> Oops, something went wrong...
Authentication Failed: OAuth login invalid or expired access token
Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

The DE has no IP restrictions.
I receive the same error when trying your button from the BoxSDK repo.
I cleared cookies, tried a different browser, etc. I get the same problem in each case.

Many thanks,
Larry

**Comment by LarryKlugerDS** [comment]
A guess is that the problem may be related to TLS 1.1 restrictions. My new DE had the restriction turned on by default. This is a change since last week or so. While I deactivated the restriction for API access, it might still be effect for OAuth operations....

**Comment by skoritsbl** [comment]
I found the way to made it work on a new Developer Editions! I deactivated the TLS 1.1 update under "Critical Updates", then I revoked all the existing authentications, logged out and cleared cookies. Now it works! For some of DE it takes a time (up to 12h) to get OAuth operations affected after TLS 1.1 disabled.

**Comment by ledfordbk** [comment]
12 hours.. ugh

**Comment by afawcett** [comment]
Thanks everyone for sharing your experiences. I have seen this issue of late as well, i suspect there is a number of root causes actually. Since the tool should not required the TLS v1.1 to be deactivated now. Is this still the case, can anyone confirm or not?

**Comment by fransflippo** [comment]
Was this ever fixed? I'm getting this error now too (it's 3 years since this issue was closed, though).

**Comment by afawcett** [comment]
@fransflippo  i did not making any changes

**Comment by fransflippo** [comment]
OK, turns out I needed to add my IP in Settings > Security > Network Access (or use a security token, but I couldn't get that to work).
Thanks!
