### ISSUE TITLE
Do not require a github login

### ISSUE THREAD

**Issue by ombr** [afawcett/githubsfdeploy#27]
Is there any way to deploy to salesforce without requiring a github account ?

I would like to use this or something similar to simplify the life of salesforce admin, but they do not have a github account.

Thanks.

**Comment by sjurgis** [comment]
Hey I am having the same issue. It's requiring ridiculous permissions full read & write to all public and private permissions!!!
@afawcett I think you just broke thousands of projects with this release.

**Comment by afawcett** [comment]
Wow ok.... i'll get onto this... 

The Private GitHub work was added by another dev, which i of course reviewed, but did not notice it seems to always want GitHub login access regardless of public or private. I did not think i regressed or changed any behaviour regarding the private GitHub support. But maybe i did.... Basically i'm going to do two things then...

A) Make sure it only needs GitHub login for Private Repos
B) Make sure when it does need GitHub login it requests the minimimum of permissions.

Sorry about this, will look into this, this weekend! 👍 

Andy

**Comment by motiko** [comment]
Hi,
Its me who implemented the private repos feature. If i remember correctly it was going to oauth process only if fetching github repository failed. In some catch block if i recall right (it was a long time ago)
Anyway let me know if you have any questions.

**Comment by afawcett** [comment]
@motiko yep, and it was me that broke it! Just found out why...so i'll push the fix shortly. One thing i cannot find though is how to change the oAuth scope permissions? I'll keep searching in the meantime...

**Comment by afawcett** [comment]
Ok, i've pushed a fix for this and opened a new issue to review the access https://github.com/afawcett/githubsfdeploy/issues/28.
