### ISSUE TITLE
deploy package to scratch org

### ISSUE THREAD

**Issue by joseph-ortiz** [afawcett/githubsfdeploy#30]
I would like a way to install a package to scratch org. When logging into the salesforce, i am returned to the githubsfdeploy page and I received the following error. I checked and the org does not have IP restrictions. The user installing the package is a system administrator

> Deploy directly from GitHub to Salesforce andyinthecloud
> Oops, something went wrong...
> Authentication Failed: OAuth login invalid or expired access token
> Be sure your Salesforce organization does not have IP restrictions. Logout and try with another user or organization.

**Comment by afawcett** [comment]
To install the package into a Scratch Org take the package ID from an install URL (see README) and use the Salesforce DX Command Line, https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_install_pkg_cli.htm

**Comment by afawcett** [comment]
Actually @joseph-ortiz i thought you ment the DLRS package, my bad. The answer above is correct if you ment "managed package" which is kind of installer for Salesforce apps. But... if you just ment code from a GitHub repo check out http://www.wadewegner.com/2017/09/deploy-to-salesforce-dx/
