### ISSUE TITLE
Lightning Web Component Missing from View

### ISSUE THREAD

**Issue by dmgerow** [afawcett/githubsfdeploy#39]
Hello,

I converted a DX project with web components and an apex class into msapi format so that I could use this button, This is my package:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <name>ApexClass</name>
    <members>RelatedQuotesController</members>
    <members>RelatedQuotesControllerTest</members>
  </types>
  <types>
    <name>LightningComponentBundle</name>
    <members>relatedQuote</members>
    <members>relatedQuotes</members>
  </types>
  <version>45.0</version>
</Package>
```

When I use the button, it pulls the data from github, but nothing from the web components folder shows
![image](https://user-images.githubusercontent.com/8942891/55522542-08b31200-564b-11e9-8163-83f303219528.png)

When I click deploy it works, so this is not a show stopper, just something I wanted to note in case it is an easy fix!

**Comment by iskilia** [comment]
I also have this issue too!

**Comment by afawcett** [comment]
@dmgerow can you confirm the repo your using? Also i have now added support for SFDX formatted repos.

**Comment by dmgerow** [comment]
@afawcett  it is in a private repository, but I tried again and it looks fixed now:
![image](https://user-images.githubusercontent.com/8942891/75792845-22b21480-5d34-11ea-9819-f3f5d6d649dc.png)
