### ISSUE TITLE
Support for private repos

### ISSUE THREAD

**Issue by afawcett** [afawcett/githubsfdeploy#4]

**Comment by motiko** [comment]
This feature will greatly benefit us. I would like to help with this.
I've created a fork and deployed to heroku but getting an error:
org.apache.jasper.JasperException: Unable to compile class for JSP: 
An error occurred at line: 1 in the generated java file
The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
==================
I guess this have some dependencies I'm missing can you please help me with that ?

**Comment by afawcett** [comment]
Fantastic, thank you so much for offering to help! :+1:

**Comment by wes1278** [comment]
So does this work now? After taking a quick look at the pull request, it seems like @motiko got it working for private Github repos?

Side thought: I would love to get this working with bitbucket. @motiko or @afawcett , any chance you could point me in the right direction for adding this support? I would love to contribute to get bitbucket supported with this tool.

Having the ability to just one-off deploy a package to an org is awesome; only catch is that github private repos are too expensive (aka not free like bitbucket)

**Comment by afawcett** [comment]
It will once merged, still working on tweaking a few implementation details, but its looking really good! 

Yeah the BitBucket API's look good, great idea.

I think we would want to build in some abstraction layer for authenticating and getting at a source control repo though, as the main class would start to get to complex i'm sure. So perhaps start with agreeing what such an interface might look like, then move out the GitHub code, implement the interface and write a small factory. We could maybe host it under another URL (e.g. bitbucketsfdeploy) with a Heroku environment var determine which source control factory to use. Thoughts gents?

**Comment by afawcett** [comment]
Ok, after a bit of playing around this morning i got this deployed. Not sure if its the best strategy retrospectively, but i have two Heroku apps one for production and one for sandbox to support this tool. As the libraries i was using didn't allow dynamic switching of the SF end points. So since the GitHub oAuth callback is now being used, i had to create a new Connected App in my GitHub config. Anyway.... It all seems to be working now... Thanks so much to @motiko !
