### ISSUE TITLE
Can't Connect to Sandbox

### ISSUE THREAD

**Issue by highered1** [afawcett/githubsfdeploy#41]
Oauth login flow for Salesforce sandbox always fails with an "oops, something went wrong" message. Have tried clearing browser history and restarting. 

<img width="1249" alt="Screen Shot 2020-01-29 at 12 31 20 PM" src="https://user-images.githubusercontent.com/60408183/73385805-67f5a900-4293-11ea-8473-e24dd9d0ecff.png">

**Comment by dpbcxc** [comment]
I am having the same issue, both with sandbox and production.

**Comment by afawcett** [comment]
@highered1 @dpbcxc can you please try again thank you. Also make sure you have a brand new browser session.

**Comment by dpbcxc** [comment]
Sorry Andy, no change:
[cid:ea2fa680-9aa9-4f98-9824-0ec23fae2746]
________________________________

**Comment by afawcett** [comment]
@dpbcxc I just tested this with a DE org ( I don't own a prod org) and it worked. Also your screenshot did not come through sadly. Was this a prod or sandbox org?

**Comment by dpbcxc** [comment]
Hi mate, I tested with both sandbox and prod, in chrome and edge – same result each time.  I am going to https://github.com/SalesforceLabs/Quick-Community-User-Provisioning and clicking the deploy from Github button.  I get redirected to the SF login, get asked for a verification code, which I enter, then the redirect seems to go temporarily to the remote access auth page (though nothing loads, it’s just in the URL bar, then I get taken to https://githubsfdeploy-sandbox.herokuapp.com/app/githubdeploy/SalesforceLabs/https:/github.com/SalesforceLabs/Quick-Community-User-Provisioning?ref=master and the status at the top right says Oops, something went wrong…

I hope this helps.  Thanks for all you do – I’ve been a long time devotee of dlrs and your blog!

[Emerging Workforce Summit - Sydney 2020]<https://www.ewsummit.com.au/>
[cid:image006.png@01D60CCC.0AA5FB80]<https://www.cxcglobal.com.au/>


Damian Blackley   Senior Salesforce Administrator
e. damian.blackley@cxcglobal.com.au
t. (03) 8374 7403
Level 8, 410 Collins Street, Melbourne VIC 3000, Australia
cxcglobal.com<http://cxcglobal.com>   [cid:image007.jpg@01D60CCC.0AA5FB80] <https://twitter.com/CXC_AUS>    [cid:image008.jpg@01D60CCC.0AA5FB80] <https://www.linkedin.com/company/cxc-global-a-nz/>

If you are not an intended recipient of this email, please notify the sender, delete it and do not act upon, print, disclose, copy, retain or redistribute it. This information may be confidential or subject to legal privilege. This documentation is for your general information, and is not to be construed as advice. Important additional terms relating to this email can be found at https://www.cxcglobal.com/en-au/terms-disclaimer

**Comment by afawcett** [comment]
Okey dokey... thanks for that... its seems to be something with that repo... at a guess something the name of it... I'll dig in! Thanks for raising. 👍

**Comment by afawcett** [comment]
This was a problem with your button config. Please update as shown below and try again...

```<a href="https://githubsfdeploy.herokuapp.com">
  <img alt="Deploy to Salesforce"
       src="https://raw.githubusercontent.com/afawcett/githubsfdeploy/master/deploy.png">
</a>```

Note if you down define the repo it will auto detected it as part of the refferal header GitHub sends. This also helps the button work on branches just fine.
