### ISSUE TITLE
Error when trying to deploy (ERROR running force:source:convert:)

### ISSUE THREAD

**Issue by ericrsmith35** [afawcett/githubsfdeploy#42]
Unhandled Exception : java.lang.RuntimeException: ERROR running force:source:convert: This command is required to run from within an SFDX project.

**Comment by ericrsmith35** [comment]
my issue

**Comment by aniketCyn** [comment]
Hey @ericrsmith35 , can you please share how you resolved this issue?

**Comment by ericrsmith35** [comment]
I'm sorry, I don't remember.
