### ISSUE TITLE
Can anyone help i need to get FFlib mocks and common deployed into production

### ISSUE THREAD

**Issue by aday12345** [afawcett/githubsfdeploy#45]
Hi, I am trying to install

https://github.com/apex-enterprise-patterns/fflib-apex-mocks/tree/master

and

https://github.com/apex-enterprise-patterns/fflib-apex-common

 I was able to about a month ago into a sandbox with no issues. And today I want to add this to our prod org but i keep getting an error when i try to install it:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

Can anyone help i need to get FFlib mocks and common deployed into production

**Comment by afawcett** [comment]
These are now working
