### ISSUE TITLE
Heroku Issue when using Deploy to Salesforce button

### ISSUE THREAD

**Issue by mitchspano** [afawcett/githubsfdeploy#46]
I am experiencing a Heroku issue when using the button:

[https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/apex-mdapi](https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/apex-mdapi)

![image](https://user-images.githubusercontent.com/18402464/115162014-8d243200-a066-11eb-8329-e041da7e3c28.png)

Please see original issue posted at - https://github.com/mitchspano/apex-trigger-actions-framework/issues/44

**Comment by afawcett** [comment]
this is now working
