### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by anjlidaryani** [afawcett/githubsfdeploy#47]
I want to install this package, I am putting forcedotcom as owner and b2b-commerce-on-lightning-quickstart
in repository and then click on 'login to salesforce' and it errors out. Can you let me know what am I doing wrong?

**Comment by afawcett** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/1167760/204441887-711e68ac-b449-4650-a36e-dc39c065e6c7.png">

**Comment by afawcett** [comment]
The sfdx-project.json needs to be in the root of the repo - this has it in /sfdx sub-directory
