### ISSUE TITLE
Auto populate the repo owner and name 

### ISSUE THREAD

**Issue by afawcett** [afawcett/githubsfdeploy#5]
When redirecting from the button on the GitHub repo README

**Comment by mshanemc** [comment]
I think this one exists already, right?

**Comment by afawcett** [comment]
Sorry yes it does, but only if the URL in the Readme passes owner and repo name, what this enhancement is about is automatically determing these without having to pass them. Which makes the use of the URL really simple. It leverages the [Refer in the HTTP header](http://en.wikipedia.org/wiki/HTTP_referer) which will contain the GitHub repo owner and name when the page is redirected to the Git Hub SF Deploy tool page.

**Comment by afawcett** [comment]
From Heroku button docs, explains why refer doesn't show in private repos...

_Resolve template implicitly. Useful on GitHub-hosted documentation. If you don’t specify a template parameter, Heroku infers it from the location of the button using the referer header (this does not work with private GitHub repos, because no referer header is sent). This makes the button stable under forks of the repository._

**Comment by afawcett** [comment]
Enhancement has now been deployed! :+1:
