### ISSUE TITLE
Getting "Failed error" alert and redirect from github to http instead of https domain.

### ISSUE THREAD

**Issue by SPaulusOfficial** [afawcett/githubsfdeploy#50]
After successfully authenticated against Salesforce and Github, I am redirected to my app "https://clickdeploy-fluent.herokuapp.com/" but with http instead of https url. All the configs contain https urls. 

If I click on "Deploy" button, I get an alert with "Failed error". If I start the full process again, it works because I am redirected to the https url.

**Comment by afawcett** [comment]
@SPaulusOfficial its probably your Connected App Callback URL I am guessing. 

btw,you know that this tool is deployed for general use here https://githubsfdeploy.herokuapp.com/ right?
